// <auto-generated />
namespace Coop_Listing_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nullable_Student_GPA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullable_Student_GPA));
        
        string IMigrationMetadata.Id
        {
            get { return "201606022037353_Nullable_Student_GPA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
