// <auto-generated />
namespace Coop_Listing_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Opportunity_Update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Opportunity_Update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201605160044292_Opportunity_Update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
